title: "The Privilege Escalation Foundation"
baseURL: "/"
languageCode: "en-US"
theme: "privilege-escalation"
tags: ["Transgender", "Nonprofit", "Support", "Resources", "Privilege"]
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

## Generic theme parameters:
Params:
  author: "The Privilege Escalation Foundation"
  description: "Elevated access to resources for determined transgender minds in STEM"

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "/images/privilege-escalation.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "favicon.png"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "The Privilege Escalation Foundation"

  # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
  #   Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
  mdTagline: "# The Privilege Escalation Foundation\n ## Elevated access to resources for brilliant **transgender** minds.{cursor}"
  favicon: "favicon.png"

  opengraphImage: "/images/privilege-escalation.png"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html'. This file will contain only a redirect directive if this switch is enabled.
  enforceSinglePage: false

  # copyright flag generates a copyright notice in footer for your site.
  copyright: true
  smallFooter: "501(c)(3) nonprofit."

## Social links in footer:
  Social:
  - type: twitter # the icon to use. can be anything mentioned in "assets/sass/_icons.scss" 
    url: "https://twitter.com/setuid_org"
  - type: github
    url: "https://github.com/privilegeescalation"
  - type: share
    url: "https://discord.gg/bnnpg6rqaJ"

## Theme features:
  Feat:
    # useLazySizes to lazy load images with lazysizes (recommended)
    useLazySizes: true

    # ajaxBasin uses Basin for a functional contact form.
    ajaxBasin: "https://usebasin.com/f/f93c92524415"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: false

    # structuredDataGitHubUser needs your USERNAME so that the GitHub API is used to fetch more information for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    #structuredDataGitHubUser = "USERNAME"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The cool thing is that the library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""
  
  Image:
    Logo:
      resize: "20x"
      

## The menu items are automatically added to navbar. Use content files for more advanced usage.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:
    - name: "About"
      identifier: about
      url: "/#about"
      weight: 1
    - name: "Resources"
      url: "/resources"
      weight: 2
    - name: "Contribute"
      url: "/contribute"
      weight: 3
    - name: "Stories"
      url: "/stories"
      weight: 4
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 5
